export type IdentityVisitor = {
  id: number;
  full_name: string;
  id_number?: string;
  document_type: string;
  birth_date?: string;
  expiry_date?: string;
  address?: string;
  created_at?: string;
  updated_at?: string;
  status?: "inside" | "outside";
  last_entry_time?: string | null;
  last_exit_time?: string | null;
  entries_count?: number;
  exits_count?: number;
  job_title?: string | null;
  department?: string | null;
  unit?: string | null;
  license_type?: string | null;
  gender?: string | null;
  nationality_en?: string | null;
  religion?: string | null;
  marital_status?: string | null;
  image_url?: string | null;
  document_image_url?: string | null;
  gate_id?: number | null;
  ocr_confidence?: number | null;
  raw_ocr_text?: string | null;
};
